# Generated by Django 5.1.5 on 2025-01-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
